@extends('app')
@section('meta')
    <meta name="description" content="Productos para mascotas directo a tu hogar, delivery con conciencia, retiramos lo que reciclas, fomentando la economía circular.">
    <!-- Google / Search Engine Tags -->
    <meta itemprop="name" content="Politicas de privacidad - Petcicla">
    <meta itemprop="description" content="Productos para mascotas directo a tu hogar, delivery con conciencia, retiramos lo que reciclas, fomentando la economía circular.">
    <meta itemprop="image" content="{{asset('storage/meta/iso.png')}}">
    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="petcicla.cl">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Politicas de privacidad - Petcicla">
    <meta property="og:description" content="Productos para mascotas directo a tu hogar, delivery con conciencia, retiramos lo que reciclas, fomentando la economía circular.">
    <meta property="og:image" content="{{asset('storage/meta/iso.png')}}">
    <!-- Twitter Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Politicas de privacidad - Petcicla">
    <meta name="twitter:description" content="Productos para mascotas directo a tu hogar, delivery con conciencia, retiramos lo que reciclas, fomentando la economía circular.">
    <meta name="twitter:image" content="{{asset('storage/meta/iso.png')}}">
@endsection
@section('css')
    <style>
        p{
            margin-bottom: 0px !important
        }
        .ql-align-center{
            text-align: center !important
        }
        .ql-align-justify{
            text-align: justify !important
        }
        .ql-align-right{
            text-align: right !important
        }
    </style>
@endsection
@section('content')
    <div class="ast-container">
        <div id="primary" class="content-area primary">
            <main id="main" class="site-main">
                <article class="post-4427 page type-page status-publish ast-article-single" id="post-4427" itemtype="https://schema.org/CreativeWork" itemscope="itemscope">
                    <header class="entry-header ast-header-without-markup"></header><!-- .entry-header -->
                    <div class="entry-content clear" itemprop="text">
                        <div class="elementor elementor-4427">
                            <div class="elementor-inner">
                                <div class="elementor-section-wrap">
                                    <section style="padding-bottom: 20px"  class="elementor-section elementor-top-section elementor-element elementor-element-a584ef8 elementor-section-content-middle elementor-reverse-mobile elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="a584ef8" data-element_type="section">
                                        <div class="elementor-background-overlay"></div>
                                        <div class="elementor-container elementor-column-gap-default">
                                            <div class="elementor-row">
                                                <div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-b7bcb4e" data-id="b7bcb4e" data-element_type="column">
                                                    <div class="elementor-column-wrap elementor-element-populated">
                                                        <div class="elementor-widget-wrap">
                                                            <div class="elementor-widget-container">
                                                                <p style="text-align:center;line-height: normal;" class="elementor-heading-title elementor-size-default"></p>
                                                                <p class="ql-align-center"><strong style="color: rgb(34, 42, 53);">CONTRATO DE PLATAFORMA DIGITAL </strong> <a href="mailto:departamentolegal@shaades.com" target="_blank" style="color: rgb(31, 56, 100);"><strong>PECICLA.CL</strong> </a></p>
                                                                <p class="ql-align-center"> <strong style="color: rgb(34, 42, 53);">CONTENIDO.</strong></p>
                                                                <p class="ql-align-center"><strong style="color: rgb(34, 42, 53);">&nbsp;</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(31, 56, 100);">PETCICLA</strong><span style="color: rgb(0, 0, 0);">&nbsp;</span><span style="color: rgb(37, 37, 37);">es una organización enfocada en ayudar a las personas a mejorar su huella verde en el planeta, entregando productos y servicios de calidad, creando conciencia de que todos somos responsables de la conservación ambiental y del planeta. Por favor lea con detenimiento el siguiente Contrato de Plataforma Digital.</span></p>
                                                                <p class="ql-align-center"><strong style="color: rgb(63, 63, 63);">&nbsp;</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);"> El siguiente contrato se aplica a todos los usuarios de</span> <strong style="color: rgb(31, 56, 100);">PETCICLA.CL</strong>. <span style="color: rgb(34, 42, 53);"> Las características, contenido, materiales, aplicaciones, productos y servicios del "sitio web" son de propiedad de </span>&nbsp; <strong style="color: rgb(31, 56, 100);">PETCICLA.CL</strong><strong style="color: rgb(190, 143, 0);">&nbsp;</strong><span style="color: rgb(34, 42, 53);">y solo a esta empresa, le pertenecen, de igual forma depende su administración. Se invita al usuario a leer estas normas, ya que describe el tipo de información que se recopila, su utilización, y las circunstancias en las que se comparte la información y cómo puede acceder, actualizar o eliminar cierta información que se recopile sobre usted. En caso de no aceptar estas normas, por favor no use el sitio web.&nbsp;Cuando usted utiliza el sitio web, entiende y acepta que se pueda recopilar, utilizar y divulgar datos e información relacionada sobre usted de varias formas, como se indica en estas normas.</span></p>
                                                                <p class="ql-align-justify">&nbsp;</p>
                                                                <p class="ql-align-right"><strong style="color: rgb(31, 56, 100);">Última actualización: este contrato entró en vigencia el 22 de Abril de 2021.</strong></p>
                                                                <p class="ql-align-right"><strong style="color: rgb(34, 42, 53);">&nbsp;</strong></p>
                                                                <p class="ql-align-center"><strong style="color: rgb(34, 42, 53);">&nbsp;</strong></p>
                                                                <p><strong style="color: rgb(0, 32, 96);">INDICE DE CONTENIDO DEL CONTRATO DE PLATAFORMA DIGITAL.</strong></p>
                                                                <p><strong>&nbsp;</strong></p><p><span style="color: rgb(31, 56, 100);">·&nbsp;</span><strong style="color: rgb(31, 56, 100);">Contrato de Plataforma Digital</strong></p>
                                                                <p><span style="color: rgb(34, 42, 53);">1.&nbsp;</span>¿Qué es el contrato de plataforma digital?</p>
                                                                <p><span style="color: rgb(34, 42, 53);">2.&nbsp;</span>Objetivos</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 176, 240);">&nbsp;</span></p>
                                                                <p><span style="color: rgb(31, 56, 100);">·&nbsp;</span><strong style="color: rgb(31, 56, 100);">Términos y Condiciones</strong></p>
                                                                <p><span style="color: rgb(34, 42, 53);">1.&nbsp;</span>Derecho de Admisión. </p>
                                                                <p><span style="color: rgb(34, 42, 53);">2.&nbsp;</span>Obligaciones de los Usuarios.</p>
                                                                <p><span style="color: rgb(34, 42, 53);">3.&nbsp;</span>¿Qué Contenidos Pertenecen a <strong>PETCICLA.CL</strong>&nbsp;y cuáles son sus usos?</p>
                                                                <p><span style="color: rgb(34, 42, 53);">4.&nbsp;</span>¿Qué Actos los Usuarios No Deben Realizar?</p>
                                                                <p><span style="color: rgb(34, 42, 53);">5.&nbsp;</span>Exoneración De Responsabilidad</p>
                                                                <p><span style="color: rgb(34, 42, 53);">6.&nbsp;</span>¿Qué Derechos Poseen los usuarios de shaades.com?</p>
                                                                <p><span style="color: rgb(34, 42, 53);">7.&nbsp;</span>Derechos de Propiedad Intelectual e Industrial</p>
                                                                <p><span style="color: rgb(34, 42, 53);">8.&nbsp;</span>Guía de uso seguro</p>
                                                                <p><span style="color: rgb(34, 42, 53);">9.&nbsp;</span>Legislación Aplicable y Jurisdicción<span style="color: rgb(0, 176, 240);">.</span></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">&nbsp;</strong></p>
                                                                <p><span style="color: rgb(31, 56, 100);">·&nbsp;</span><strong style="color: rgb(31, 56, 100);">Políticas de Protección de Datos</strong></p>
                                                                <p><strong style="color: rgb(34, 42, 53);">NORMAS SOBRE PROTECCIÓN DE DATOS Y DECLARACIONES DE CONSENTIMIENTO</strong></p>
                                                                <p><span style="color: rgb(34, 42, 53);">1.&nbsp;</span>Uso informativo del sitio web.</p>
                                                                <p><span style="color: rgb(34, 42, 53);">2.&nbsp;</span>Acopio y utilización de los datos para el tratamiento de los contratos.</p>
                                                                <p><span style="color: rgb(34, 42, 53);">3.&nbsp;</span>Registro de cuenta</p>
                                                                <p><span style="color: rgb(34, 42, 53);">4.&nbsp;</span>Recopilación y uso de datos con fines de publicidad y de marketing directo</p>
                                                                <p><span style="color: rgb(34, 42, 53);">5.&nbsp;</span>Políticas en redes sociales</p>
                                                                <p><span style="color: rgb(34, 42, 53);">6.&nbsp;</span>Administración de la información de los usuarios. </p>
                                                                <p><span style="color: rgb(34, 42, 53);">7.&nbsp;</span>seguridad jurídica de la política de privacidad de datos</p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">&nbsp;</strong></p>
                                                                <p><span style="color: rgb(31, 56, 100);">·&nbsp;</span><strong style="color: rgb(31, 56, 100);">Políticas de Cookies </strong></p>
                                                                <p><span style="color: rgb(34, 42, 53);">1.&nbsp;</span>¿Qué son las cookies?</p><p><span style="color: rgb(34, 42, 53);">2.&nbsp;</span>¿Cuáles son las funciones de las cookies?</p>
                                                                <p><span style="color: rgb(34, 42, 53);">3.&nbsp;</span>¿Qué no es una cookie?</p>
                                                                <p><span style="color: rgb(34, 42, 53);">4.&nbsp;</span>¿Qué información almacena una&nbsp;cookie?</p>
                                                                <p><span style="color: rgb(34, 42, 53);">5.&nbsp;</span>Tipos o clases de&nbsp;cookies</p>
                                                                <p><span style="color: rgb(34, 42, 53);">6.&nbsp;</span>Consecuencias de la desactivación de las cookies.</p>
                                                                <p><span style="color: rgb(34, 42, 53);">7.&nbsp;</span>Desactivación o eliminación de cookies</p>
                                                                <p><span style="color: rgb(34, 42, 53);">8.&nbsp;</span>Exclusión de responsabilidades en cuanto al manejo de las cookies.</p>
                                                                <p><span style="color: rgb(34, 42, 53);">9.&nbsp;</span>Consentimiento sobre el uso de las cookies por parte de los usuarios</p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">&nbsp;</strong></p>
                                                                <p><span style="color: rgb(31, 56, 100);">·&nbsp;</span><strong style="color: rgb(31, 56, 100);">CONTRATO DE PLATAFORMA DIGITAL</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">¿Qué es el contrato de plataforma digital?</strong></p>
                                                                <p class="ql-align-justify">“Son un <em>conjunto de normas de carácter contractual, de obligatorio cumplimiento, y jurídicamente aplicables para los usuarios, clientes y visitantes de la página web de </em><strong style="color: rgb(31, 56, 100);"><em><u>PETCICLA.CL</u></em></strong><em>, cualquiera que sea su rol, (individuo, persona natural, empresas o personas jurídicas y el personal de la empresa), que van a regir la conducta de los usuarios dentro de las plataformas tecnológicas que se desarrollen para la prestación del servicio, ampliándose dentro de estas normas los derechos, beneficios que tendrán los usuarios en el uso de la página web, así como también las obligaciones que los usuarios que deberán cumplir para el correcto manejo </em><strong><em>del sitio web</em>”. </strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">En concordancia con lo establecido en el Código Civil Chileno.</strong></p>
                                                                <p class="ql-align-justify"><strong><em>“</em></strong><strong style="color: rgb(34, 42, 53);"><em>Artículo 1438</em></strong><strong><em>. Contrato o convención es un acto por el cual una parte se obliga para con otra a dar, hacer o no hacer alguna cosa. Cada parte puede ser una o muchas personas.”</em></strong></p>
                                                                <p class="ql-align-justify"><strong><em>“</em></strong><strong style="color: rgb(34, 42, 53);"><em>Artículo 1445</em></strong><strong><em>. Para que una persona se obligue a otra por un acto o declaración de voluntad es necesario:1º que sea legalmente capaz; 2º que consienta en dicho acto o declaración y su</em></strong><em>&nbsp;consentimiento no adolezca de vicio; 3º que recaiga sobre un objeto lícito; 4º que tenga una causa lícita.</em></p>
                                                                <p class="ql-align-justify"><em>La capacidad legal de una persona consiste en poderse obligar por sí misma, y sin el ministerio o la autorización de otra.”</em></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
                                                                <p class="ql-align-justify">La naturaleza del presente contrato es de adhesión. El usuario tiene la obligación de leer y respetar cada una de las normas aquí presentes, en caso de que el usuario incumpla cualquier norma presente en este contrato, nos reservamos el derecho de admisión y las acciones judiciales a que hubiere lugar de ejecutar por incumplimiento de las mismas. </p>
                                                                <p class="ql-align-center"><strong style="color: rgb(0, 32, 96);">&nbsp;</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">ESTRUCTURA CONTRACTUAL.</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">&nbsp;</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);"><u>EL PRESENTE CONTRATO ESTÁ COMPUESTO POR:</u></strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">&nbsp;</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">1.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Términos y Condiciones</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">2.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Políticas de Protección</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">3.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Políticas Cookies.</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(0, 32, 96);">&nbsp;</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">OBJETIVOS.</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">El objetivo,&nbsp;es mantener informado al público general a todos nuestros clientes, proveedores y personal, para alcanzar niveles óptimos de seguridad de la información que estos nos suministren para los procesos críticos de los servicios de la empresa. Este Contrato de Plataforma Digital, </span>es<span style="color: rgb(0, 0, 0);">&nbsp;el resultado de consultas e investigación legal pertinente en el marco del Derecho Privado, Derecho Contractual, Derecho Civil, Mercantil, Internacional Privado, Internacional Público, Marco Jurídico Internacional en relación con las normas de protección de Datos. </span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">·&nbsp;</span><strong style="color: rgb(31, 56, 100);">TERMINOS Y CONDICIONES DE USO DE LA PÁGINA WEB</strong><strong style="color: rgb(50, 62, 79);">.&nbsp;</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(50, 62, 79);">&nbsp;</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">Los términos y condiciones de esta página web, tienen por finalidad facilitar al usuario información relativa a los productos y servicios prestados por la empresa, además mostrar las actividades que se desempeñan, las noticias relativas a su actividad, así como las distintas áreas de negocio.</span></p>
                                                                <p class="ql-align-justify">&nbsp;</p><p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">El carácter del sitio web, es informativo y comercial. El Usuario al navegar, accede a la información publicada en esta plataforma, la&nbsp;acción de navegar y acceder a la información que se presenta, supone la aceptación, expresa y tacita de todas las normativas legales, sin reservasde ninguna clase. En el caso de no aceptarlas, le pedimos inhibirse de utilizar esta plataforma y todo su contenido.</span><strong style="color: rgb(31, 56, 100);"><em><u>&nbsp;PETCICLA.CL</u></em></strong>, es la empresa encargada de administrar este sitio web, y podrá, en todo momento y sin previo aviso, modificar los presentes normativas. Esta decisión de modificar los presentes términos y condiciones se realizaran por exigencias de la leyes, cuando el ordenamiento jurídico de Chile sea objeto de reforma, modificaciones o le entrada en vigencia de una nueva ley. También podrán ser modificados cuando las leyes internacionales para una mejor salvaguarda en el tema de la&nbsp;protección de datos personales, la privacidad y la sociedad de la información así lo exijan, y por último, podrán ser modificados por decisión de la directiva de la empresa. Las modificaciones resultantes serán publicadas en este sitio web.</p>
                                                                <p class="ql-align-justify">&nbsp;</p><p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">DERECHO DE ADMISIÓN. ACCESO Y UTILIZACIÓN</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">ACCESO: </strong>Este sitio web, podrá, en todo momento, expulsar o denegar el acceso al sitio web a los usuarios que hagan un mal uso de las normativas. El acceso a la página web es gratuito, salvo en lo relativo al coste de la conexión suministrada por el proveedor de servicio contratado por el usuario. </p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(31, 56, 100);">UTILIZACIÓN</strong><strong style="color: rgb(50, 62, 79);">: </strong>El usuario está obligado a respetar las normas hacer un correcto uso de la página web y de todo su contenido, apegado a las leyes y los valores.</p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(50, 62, 79);">&nbsp;</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">OBLIGACIONES DE LOS USUARIOS.</strong></p>
                                                                <p><span style="color: rgb(34, 42, 53);">1.&nbsp;</span>Todos los usuarios y sin discriminación alguna, son responsables de su conducta, al acceder a la información de la plataforma web, mientras naveguen o accedan en la página web, así como después de haber accedido a ella.</p>
                                                                <p><span style="color: rgb(34, 42, 53);">2.&nbsp;</span>El usuario está obligado en todo momento a la correcta utilización del sitio web y será el único responsable del mal manejo de la información de la presente plataforma ante las leyes de la república sin el menos cabo de las leyes internacionales. </p>
                                                                <p><span style="color: rgb(34, 42, 53);">3.&nbsp;</span>El usuario de igual forma, está obligado en todo momento y sin ningún tipo de discriminación a cumplir a cabalidad los presentes Términos y Condiciones, las instrucciones y avisos que se le comuniquen por medio de la página web, así como de respetar la moral y las buenas costumbres generalmente aceptadas y preservar el orden público.</
                                                                <p><span style="color: rgb(34, 42, 53);">4.&nbsp;</span>El usuario se obliga a hacer uso exclusivo de esta página web, así como de todo su contenido, para fines lícitos y no prohibidos por la ley.</p>
                                                                <p><span style="color: rgb(34, 42, 53);">5.&nbsp;</span>El usuario no podrá de ninguna forma realizar acciones u actos en base al contenido de la página web, que puedan resultar lesivos de los derechos legítimos de la empresao de cualquier <strong>tercero</strong>&nbsp;que puedan causar daños o perjuicios de forma directa o indirecta.</p>
                                                                <p>&nbsp;</p><p>&nbsp;</p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">¿QUÉ CONTENIDOS PERTENECEN A </strong><strong style="color: rgb(31, 56, 100);">PETCICLA.CL</strong><strong style="color: rgb(34, 42, 53);">?</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">Los textos, fotografías, códigos fuente, audiovisuales, sonido, video, gráficos, diseño gráfico imágenes, iconos, tecnología, software, tipografía, links y en general todoel contenido que en esta página web sean incorporados.</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">&nbsp;</span></p><p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">¿QUÉ ACTOS LOS USUARIOS NO DEBEN REALIZAR?</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">Los usuarios deberán de abstenerse de realizar actos, que:</strong></p>
                                                                <p class="ql-align-justify">1.&nbsp;Induzcan, inciten o promuevan actuaciones delictivas, difamatorias, violentas o, en general, contrarias a la Ley, a la moral y buenas costumbres generalmente aceptadas o al orden público.</p>
                                                                <p class="ql-align-justify">2.&nbsp;Que sean falsos, ambiguos, inexactos, exagerados o extemporáneos, de forma que induzcan o puedan inducir a error sobre su objeto o sobre las intenciones o propósitos del comunicante.</p>
                                                                <p class="ql-align-justify">3.&nbsp;De manipulación de elementos que se encuentren protegidos por los derechos de propiedad intelectual o industrial pertenecientes a o terceros, sin que el usuario haya obtenido previamente de sus titulares la autorización necesaria para llevar a cabo el uso que efectúa o pretende efectuar. </p>
                                                                <p class="ql-align-justify">4.&nbsp;Constituyan, en su caso, publicidad ilícita, engañosa o desleal y, en general, que constituyan competencia desleal o vulneren las normas reguladoras de la protección de datos de carácter personal.</p>
                                                                <p class="ql-align-justify">5.&nbsp;Incorporen virus, malware, gusanos, troyanos u otros elementos físicos o electrónicos que puedan dañar o impedir el normal funcionamiento de la red, del sistema o de equipos informáticos (hardware y software)</p>
                                                                <p class="ql-align-justify">6.&nbsp;Provoquen por sus características, incluir formatos o extensión, que dificulten el normal funcionamiento de los servicios ofrecidos por esta plataforma.</p>
                                                                <p class="ql-align-justify">7.&nbsp;El usuario responderá de los daños y perjuicios de toda naturaleza que la empresa, pueda sufrir como consecuencia del incumplimiento de cualquiera de las obligaciones a las que queda sometido en virtud de los presentes Términos y Condiciones o de la legislación aplicable en relación con la utilización de la página web.</p>
                                                                <p class="ql-align-justify">&nbsp;</p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">EXONERACIÓN DE RESPONSABILIDAD.</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">Estas exoneraciones están establecidas en las leyes nacionales e internacionales, de acuerdo a las acciones realizadas enteramente por los usuarios quienes son responsables en todo momento por sus acciones u omisiones. Los usuarios son personas naturales&nbsp;y jurídicas quienes se declaran así mismos enteramente actos civiles, penales y administrativamente en lo que hubiera lugar. A título enunciativo y no limitativo, </span><strong>La empresa </strong><span style="color: rgb(0, 0, 0);">no asumirá responsabilidad alguna:</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">1.&nbsp;</span>Del maluso que los usuarios puedan hacer,con respecto al contenido de esta página web,&nbsp;que infrinjan los derechos de propiedad intelectual o industrial de contenidos de la plataforma o de terceros.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">2.&nbsp;</span>De los daños y perjuicios causados por un funcionamiento normal o anormal de las herramientas de esta plataforma, o de los errores o problemas que se generen en el desarrollo de los elementos técnicos que el sitio web o un programa facilite al usuario.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">3.&nbsp;</span>De los contenidos de aquellas páginas web a las que los usuarios puedan acceder desde enlaces incluidos en el sitio web de un tercero, ya sean autorizados o no.</p>
                                                                <p class="ql-align-justify">&nbsp;</p><p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">LA EMPRESA NO GARANTIZA LO SIGUIENTE:</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">Que el acceso a la página web sea ininterrumpido, dado que podrían existir dificultades técnicas por terceros, quienes son los prestadores de servicios de internet y el Hosting donde se almacena la página web.</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">Que los usuarios accedan a nuestra la página web pormedio de enlaces no oficiales, proporcionados por terceros,y que estos no contengan error alguno, virus informático u otros elementos que puedan producir alteraciones o daños en sus sistemas.</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">¿QUÉ DERECHOS POSEEN LOS USUARIOS?</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">1.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Derecho de acceso</strong><span style="color: rgb(0, 0, 0);">: Es la facultad que tiene una persona natural o jurídica, para acceder a la información contenida en esta página web,con la obligación de cumplir con todas las exigencias de ley, términos y condiciones y demás normas complementarias para tal fin. </span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">2.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Derecho de rectificación:</strong><span style="color: rgb(0, 0, 0);">Es la facultad que tiene el titular de los datos personales de modificar, reparar, enmendar, remediar, resarcir, los datos que previamente haya suministrado debido a un error, ya sea de transcripción, ortográfico o de cualquier naturaleza.</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">3.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Derecho de cancelación</strong><strong style="color: rgb(0, 0, 0);">:</strong><span style="color: rgb(0, 0, 0);">&nbsp;Es el derecho que tiene todo usuario a la supresión de los datos personales, comúnmente conocido como “derecho al olvido”, derecho de un usuario al borrado de sus datos personales que este haya suministrado a un medio digital, página web, red social, aplicaciones móviles, programas informáticos, video juegos, cualquiera que sea. </span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">4.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Derecho de oposición:</strong><span style="color: rgb(0, 0, 0);">Es la facultad que tiene el titular de los datos personales de negarse u oponerse a suministrarlos.</span></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">¿Cómo ejercer mis Derechos como usuario?</strong><strong style="color: rgb(0, 0, 0);">	</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">Para realizar algún reclamo, el usuario debe iniciar el proceso dirigiéndose a la empresa por vía de los medio corporativos que la empresa pone a su disposición, debe señalar con precisión el derecho que se ejerce, incluir sus documentos de identificación nacional o pasaporte vigente. </span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">DERECHOS DE PROPIEDAD INTELECTUAL E INDUSTRIAL.</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(31, 56, 100);"><em><u>PETCICLA.CL</u></em></strong><span style="color: rgb(0, 0, 0);">&nbsp;se reserva todos los derechos sobre todo el contenido; diseño, código fuente&nbsp;y, en especial, con carácter enunciativo pero no limitativo, sobre las fotografías, imágenes, textos, logos, diseños, marcas, nombres comerciales y datos que se incluyen en la página web y futuras aplicaciones móviles. Se advierte a los usuarios que estos derechos están protegidos por la legislación de Chile actualmente vigente y la legislación e internacional relativa a la propiedad intelectual e industrial. Queda expresamente prohibida la reproducción total o parcial de esta página web, y de cualquiera de sus contenidos, sin la autorización expresa y por escrito de </span><strong style="color: rgb(31, 56, 100);"><em><u>PETCICLA.CL</u></em></strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">GUÍA DE USO SEGURO.</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">PHISHING</strong>; Es una técnica de ingeniería social utilizada por los delincuentes para obtener información confidencial como nombres de usuario, contraseñas y detalles de tarjetas de crédito haciéndose pasar por una comunicación confiable y legítima.</p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">&nbsp;</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">CÓMO EVITAR EL PHISHING:</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">1.&nbsp;</span>Mantenga buenos hábitos y no responda a enlaces en correos electrónicos no solicitados </p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">2.&nbsp;</span>No abra adjuntos de correos electrónicos no solicitados.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">3.&nbsp;</span>Proteja sus contraseñas y no las revele a nadie.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">4.&nbsp;</span>No proporcione información confidencial a nadie por teléfono, en persona o a&nbsp;través del correo electrónico.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">5.&nbsp;</span>Compruebe la URL del sitio (dirección web). En muchos casos de phishing, la dirección web puede parecer legítima, pero la URL puede estar mal escrita o el dominio puede ser diferente (.com cuando debería ser .gov).</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">6.&nbsp;</span>Ninguna entidad, empresa o servicio con buena reputación solicitará datos de acceso a sus cuentas online u otros datos relacionados con el usuario bajo ninguna excusa a través del correo electrónico. Si se recibe un mensaje en este sentido, hay que eliminarlo. En caso de duda, siempre se puede preguntar a través de los canales oficiales directamente a la empresa o servicio mencionado</p>
                                                                <p class="ql-align-justify">&nbsp;</p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">EXCLUSIÓN DE RESPONSABILIDAD: </strong><strong style="color: rgb(31, 56, 100);"><em><u>PETCICLA.CL</u></em></strong>&nbsp;declara que no realiza acciones que tengan relación con ningún tipo de técnicas ilegales y no es responsable de cualquier información que sea obtenida por esta vía ilícita. Procuramos la seguridad de los bienes de la información de cada uno de&nbsp;nuestros usuarios y la&nbsp;tratamos&nbsp;con&nbsp;el mayor&nbsp;respeto y responsabilidad</p>
                                                                <p class="ql-align-justify">&nbsp;</p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">LEGISLACIÓN APLICABLE Y JURISDICCIÓN.</strong></p>
                                                                <p class="ql-align-justify">El acceso y utilización de la&nbsp;página web se regirá e interpretará de conformidad con la legislación Chilena e internacional. Cualquier controversia que pudiera surgir con los usuarios, será dirimida, por las partes por los Juzgados y Tribunales de la República de Chile.</p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">MARCO JURÍDICO APLICABLE</strong>:</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">1.&nbsp;</span><strong style="color: rgb(34, 42, 53);">NUMERAL CUARTO (4TO) ARTICULO 19 CONSTITUCIÓN CHILENA</strong>. El respeto y protección a la vida privada y a la honra de la persona y su familia, y asimismo, la protección de sus datos personales. El tratamiento y protección de estos datos se efectuará en la forma y condiciones que determine la ley”.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">2.&nbsp;</span><strong style="color: rgb(34, 42, 53);">LEY N° 19.628.&nbsp;PROTECCIÓN DE DATOS DE CARÁCTER PERSONAL</strong>. Esta ley, es el cuerpo legal directamente aplicable a esta materia de forma general. La ley regula el “tratamiento de los datos de carácter personal en registros o bancos de datos por organismos públicos o por particulares.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">3.&nbsp;</span><strong style="color: rgb(34, 42, 53);">REGLAMENTO GENERAL DE PROTECCIÓN DE DATOS</strong>. El RGPD establece los requisitos específicos para empresas y organizaciones sobre recogida, almacenamiento y gestión de los datos personales. Se aplican tanto a las organizaciones europeas que tratan datos personales de ciudadanos en la&nbsp;<a href="#abbr-ID0E1" target="_blank">UE</a>&nbsp;como a las organizaciones que tienen su sede fuera de la UE y cuya actividad se dirige a personas que viven en la UE.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">4.&nbsp;</span><strong style="color: rgb(34, 42, 53);">LOS PRINCIPIOS GENERALES DEL DERECHO.</strong>Las normas en el Derecho Internacional Público, el artículo 38.1.Literal (C) del Estatuto de la&nbsp;Corte Internacional de Justicia&nbsp;considera a los principios generales del derecho una&nbsp;fuente formal&nbsp;del derecho internacional, al lado de la&nbsp;costumbre internacional&nbsp;y los&nbsp;tratados internacionales, por lo cual los tribunales de justicia estarían obligados.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(31, 56, 100);">·&nbsp;</span><strong style="color: rgb(34, 42, 53);">POLÍTICA DE DATOS DE </strong><strong style="color: rgb(31, 56, 100);">PETCICLA.CL</strong></p>
                                                                <p class="ql-align-justify">&nbsp;</p>
                                                                <p class="ql-align-justify">La página&nbsp;<strong style="color: rgb(31, 56, 100);"><em><u>PETCICLA.CL</u></em></strong>&nbsp;reconoce la importancia de identificar y proteger sus activos de la información, evitando la destrucción, divulgación, modificación y utilización no autorizada de toda la información relacionada con sus clientes y usuarios, la información de nuestros clientes es un elemento esencial de la prestación de nuestros servicios. </p>
                                                                <p class="ql-align-justify"><span style="color: rgb(59, 56, 56);">&nbsp;</span></p>
                                                                <p>I<strong style="color: rgb(34, 42, 53);">NFORMACIÓN BÁSICA SOBRE PROTECCIÓN DE DATOS DE </strong><a href="mailto:departamentolegal@shaades.com" target="_blank">PETCICLA.CL</a></p>
                                                                <p><strong style="color: rgb(34, 42, 53);">Responsable</strong></p>
                                                                <p><strong style="color: rgb(31, 56, 100);"><em><u>PETCICLA.CL</u></em></strong></p>
                                                                <p><strong style="color: rgb(34, 42, 53);">Finalidad</strong></p>
                                                                <p>Llevar a cabo el desarrollo de los servicio&nbsp;con las comunicaciones que ello conlleva, realizar la atención de solicitudes de diversa índole por parte del Usuario y el envío de información acerca de nuestros servicios.</p>
                                                                <p><strong style="color: rgb(34, 42, 53);">Legitimación</strong></p>
                                                                <p>Consentimiento del interesado. Apoyado con el marco jurídico de Chile, con la Ley N°19.628&nbsp;Protección de Datos de Carácter Personal., el Reglamento General de Protección de Datos de la Unión Europea, llamado por sus siglas (RGPD). Y el marco jurídico internacional.</p>
                                                                <p><strong style="color: rgb(34, 42, 53);">Destinatarios&nbsp;</strong></p>
                                                                <p>Personas naturales y jurídicas de todo tipo, entidades públicas&nbsp;o privadas relacionados con el servicio, y otras entidades necesarias para llevar a cabo igualmente la prestación del mismo. (clientes, usuarios, trabajadores de la empresa, público en general)</p>
                                                                <p><strong style="color: rgb(34, 42, 53);">Derechos</strong></p>
                                                                <p>Acceder, Rectificar y Suprimir los Datos, así como otros derechos, como se explica en la Información Adicional</p>
                                                                <p><strong style="color: rgb(34, 42, 53);">Información adicional</strong></p>
                                                                <p>Consulte la Información Adicional y detallada sobre Protección de Datos. A través de los medios corporativos de la Empresa. </p>
                                                                <p class="ql-align-justify"><strong>&nbsp;</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">NORMAS SOBRE PROTECCIÓN DE DATOS Y DECLARACIONES DE CONSENTIMIENTO.</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(31, 56, 100);">PETCICLA<em><u>&nbsp;</u></em></strong>es el operador del sitio web&nbsp;<strong style="color: rgb(31, 56, 100);"><em><u>PETCICLA.CL</u></em></strong>, es responsable de los datos personales de los usuarios del Sitio web, en el sentido o de acuerdo a lo establecido en la Ley N°19.628&nbsp;Protección de Datos de Carácter Personal., y del Reglamento General de Protección de Datos de la Unión Europea, llamado por sus siglas (RGPD).</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">·&nbsp;</span><strong style="color: rgb(34, 42, 53);">USO INFORMATIVO DEL SITIO WED.</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">Todas las personas que accedan a nuestro sitio web lo podrán utilizar. Cada vez que se accede a una página web, el servidor web simplemente almacena automáticamente los datos de acceso en los archivos de registro del servidor que su navegador comunica automáticamente, como el nombre del archivo solicitado, la última página web visitada, la fecha y hora de acceso, el navegador utilizado, el volumen de datos transmitido, la dirección IP y el proveedor solicitante. El servidor web no almacena estos datos. Como parte del procesamiento en nuestro nombre, un proveedor externo nos proporciona servicios de alojamiento y presentación de sitios web. </span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">&nbsp;</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">·&nbsp;</span><strong style="color: rgb(34, 42, 53);">ACOPIO Y UTILIZACIÓN DE LOS DATOS PARA EL TRATAMIENTO DE LOS CONTRATOS.</strong></p>
                                                                <p class="ql-align-justify">En cuanto a la recopilación de datos personales cuando se pone en contacto con nosotros (por ejemplo, a través de un formulario de contacto o correo electrónico), cuando se registra en una cuenta de usuario o en el marco de su reserva. Los datos que se recogen en detalle y los que son obligatorios y voluntarios se pueden ver en los respectivos formularios de entrada.</p>
                                                                <p class="ql-align-justify">&nbsp;</p>
                                                                <p><span style="color: rgb(34, 42, 53);">·&nbsp;</span><strong style="color: rgb(34, 42, 53);">REGISTRO de CUENTA </strong></p>
                                                                <p class="ql-align-justify">En <strong style="color: rgb(31, 56, 100);"><em><u>PETCICLA.CL</u></em></strong>&nbsp;no registramos cuentas de usuarios, los datos que recopilemos de nuestros usuarios son directamente proporcionados mediante formularios de contactos o por el suministro de sus datos por vía de algunos de nuestros medios de información.</p>
                                                                <p><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
                                                                <p><strong style="color: rgb(34, 42, 53);">Razones por la cual la empresa procesa sus datos:</strong></p>
                                                                <p><span style="color: rgb(34, 42, 53);">·&nbsp;</span>Para suministrar, proveer o prestaralgún servicio que usted solicite. </p>
                                                                <p><span style="color: rgb(34, 42, 53);">·&nbsp;</span>Para cumplir con nuestras obligaciones derivadas de los contratos, como facturación.</p>
                                                                <p><strong style="color: rgb(34, 42, 53);">Publicación de los datos: </strong>Su data personal no será publicada. Esto siempre enmarcado en la legislación Chilena y en la Ley n° 19.628. Protección de Datos de Carácter Personal de la RGPD Unión Europea.</p>
                                                                <p><strong style="color: rgb(34, 42, 53);">Eliminación de datos:</strong>Terminada la relación de prestación de servicio generada por contratación sus datos personales son eliminados de la plataforma.</p>
                                                                <p><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
                                                                <p><strong style="color: rgb(34, 42, 53);">RECOPILACIÓN Y USO DE DATOS CON FINES DE PUBLICIDAD Y DE MARKETING DIRECTO</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">Publicidad</strong><strong>.</strong>Por medio de la información suministrada por los usuarios, y siempre contado en todo momento con su consentimiento, podremos enviar ofertas comerciales e información sobre nuestros productos por correo electrónico, teléfono o cualquier otro medio suministrado. Esto sirve para proteger nuestros intereses legítimos en un enfoque publicitario hacia nuestros clientes de conformidad con <span style="color: rgb(0, 0, 0);">Ley n° 19.628. Protección de Datos de Carácter Personal&nbsp;de la RGPD Unión Europea</span>, que predomina en el contexto de una ponderación de intereses. Usted puede oponerse al almacenamiento y uso de su información en cualquier momento enviando un mensaje a&nbsp;nuestros medio corporativos.</p>
                                                                <p class="ql-align-justify"><strong>&nbsp;</strong></p>
                                                                <p><strong style="color: rgb(34, 42, 53);">POLÍTICAS EN REDES SOCIALES</strong></p>
                                                                <p class="ql-align-justify">La página web de <strong style="color: rgb(31, 56, 100);"><em><u>PETCICLA.CL</u></em></strong>&nbsp;contiene el uso de plugins, widgetso enlaces para acceder directamente a sus redes sociales. Si hace clic en uno de los enlaces, se abrirá una nueva ventana de su navegador del proveedor de servicio. La recolección de datos, el tratamiento y uso posterior por parte de los proveedores, y la posibilidad de contacto y sus derechos relevantes y opciones de configuración para la protección de su privacidad se pueden encontrar en la información de protección de datos de los proveedores:</p>
                                                                <p>&nbsp;</p>
                                                                <p><span style="color: rgb(34, 42, 53);">·&nbsp;</span><a href="http://www.facebook.com/policy.php" target="_blank">Advertencia sobre protección de datos de Facebook</a></p>
                                                                <p><span style="color: rgb(34, 42, 53);">·&nbsp;</span><a href="https://twitter.com/privacy" target="_blank">Advertencia sobre protección de datos de Twitter</a></p>
                                                                <p><span style="color: rgb(34, 42, 53);">·&nbsp;</span><a href="https://help.instagram.com/155833707900388" target="_blank">Advertencia sobre protección de datos de Instagram</a></p>
                                                                <p><span style="color: rgb(34, 42, 53);">·&nbsp;</span><a href="https://www.linkedin.com/legal/privacy-policy?trk=uno-reg-guest-home-privacy-policy" target="_blank">Advertencia sobre protección de datos de Linkedin</a></p>
                                                                <p><span style="color: rgb(34, 42, 53);">·&nbsp;</span><a href="https://policies.google.com/privacy?hl=es-419&amp;gl=mx" target="_blank">Advertencia sobre protección de datos de Youtube</a></p>
                                                                <p><span style="color: rgb(95, 103, 107);">&nbsp;</span></p>
                                                                <p><strong style="color: rgb(34, 42, 53);">ADMINISTRACIÓN DE LA INFORMACIÓN DE LOS USURIOS. </strong></p>
                                                                <p><strong style="color: rgb(34, 42, 53);">Transferencia de datos</strong>.Lainformación que los usuarios suministran,podrá ser transmitida a terceras personas, solo con fines operacionales, logísticos y comerciales, para una mejor prestación de servicios, para la elaboración de contratos, garantías, facturas, acuerdos o documentos legales, que usted requiera, siempre y cuando el usuario haya dado su consentimiento de acuerdo con la Ley n° 19.628. Protección de Datos de Carácter Personal y de la RGPD Unión Europea.</p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">Acopio de datos</strong>.Contando con su consentimiento,de conformidad con la Ley n° 19.628. Protección de Datos de Carácter Personal y el artículo 6, literal (A) del RGPD de la Unión Europea, los datos relativos a los contratos y acuerdos que usted contraiga con la Empresa se almacenarán y utilizarán en archivos (durante un máximo de 10 años) con el fin de comprobar la autenticidad y emitir certificados de sustitución. El tratamiento de datos personales en países no pertenecientes a la Unión Europea o al Espacio Económico Europeo se basa en la necesidad de transmitirlos para la diligencia del presente acuerdo o contrato de aceptación a estas políticas de protección de datos que se le presenta y de aquellos contratos y acuerdo que usted realice o contraiga con la empresa.</p>
                                                                <p><strong style="color: rgb(34, 42, 53);">&nbsp;</strong></p><p><strong style="color: rgb(34, 42, 53);">DOCUMENTOS Y REQUISITOS QUE PODRÁN SER EXIGIDOS PARA EL ACOPIO DE DATOS CON FINES CONTRACTUALES:</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">1.&nbsp;</span>Datos personales: (nombres, apellidos, estado civil, dirección de habitación, domicilio, fecha de nacimiento, números telefónicos, correos electrónicos, números de documentos de identificación, numero de pasaportes, entre otros documentos que sean necesarios de acuerdo a las leyes)</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">2.&nbsp;</span>Copias electrónicas del pasaporte o documentos de identificación</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">3.&nbsp;</span>Foto personal en la que sea visible el rostro de la persona</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">4.&nbsp;</span>Cualquier otro documento o requisito que sea necesario incluir.</p>
                                                                <p><span style="color: rgb(71, 171, 216);">&nbsp;</span></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">EXACTITUD DE DATOS.</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">Para protegerla integridad personal de los usuarios y la integridad de la Empresa,es necesario que los </span><span style="color: rgb(34, 42, 53);">usuarios nos proporcionen su información exacta, clara y sin errores, para evitar </span><span style="color: rgb(0, 0, 0);">la pérdida, destrucción, acceso, modificación, falsedad de la información, adulteración de datos, fraude&nbsp;o distribución de sus datos por parte de personas no autorizadas. Al respecto la Ley n° 19.628. Protección de Datos de Carácter Personal en su&nbsp;Artículo 6 establece lo siguiente. “Los datos personales deberán ser eliminados o cancelados cuando su almacenamiento carezca de fundamento legal o cuando hayan caducado. Han de ser modificados cuando sean erróneos, inexactos, equívocos o incompletos. Se bloquearán los datos personales cuya exactitud no pueda ser establecida o cuya vigencia sea dudosa y respecto de los cuales no corresponda la cancelación. El responsable del banco de datos personales procederá a la eliminación, modificación o bloqueo de los datos, en su caso, sin necesidad de requerimiento del titular”. Sin menos cabo de las disposiciones legales que establezca el RGPD de la Unión Europea.</span></p>
                                                                <p><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
                                                                <p><strong style="color: rgb(34, 42, 53);">SEGURIDAD JURIDICA DE LA POLÍTICA DE PRIVACIDAD DE DATOS</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(31, 56, 100);"><em><u>PETCICLA.CL</u></em></strong>&nbsp;de acuerdo a lo establecido en la Ley N°19.628 sobre Protección de la Vida Privada, considerando los principios constitucionales en materia de protección de datos contenidos en el Numeral cuarto (4to) artículo 19 de la Constitución Chilena, se garantiza el respeto y protección a la vida privada, a la honra de la persona, su familia, y la protección de sus datos personales. <strong style="color: rgb(31, 56, 100);"><em><u>PETCICLA.CL</u></em></strong>&nbsp;informa a todos los usuarios que el tratamiento de datos personales que se realiza en el portal web se rige por las siguientes normas:</p>
                                                                <p class="ql-align-justify">&nbsp;</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">1.&nbsp;</span>Se garantiza que el tratamiento de los datos personales de los usuarios se efectuará conforme a la finalidad para la cual son recolectados. </p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">2.&nbsp;</span>En el caso de que algún ente u órgano público del Estado Chileno, descritos en el Artículo 2 de la Ley de Transparencia de la Función Pública y de Acceso a la Información de la Administración del Estado, aprobada por el artículo primero de la Ley N° 20.285, en adelante Ley de Transparencia, haya ingresado datos a nuestra plataforma web con el fin de contratar alguno de nuestros servicios, estos datos podrán ser utilizados por la empresa para los efectos de cumplimiento con las leyes de la república, por razones legales y contractuales con los órganos del estado Chileno.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">3.&nbsp;</span><span style="color: rgb(0, 0, 0);">Los datos personales de los usuarios ingresados en esta página web serán utilizados únicamente para el cumplimiento de los fines indicados en los formularios de contacto y la correspondiente política de datos.Ley N°19.628, Artículo 3.</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">4.&nbsp;</span>Los datos personales de los usuarios (personas naturales y personas jurídicas de carácter privado, entes u órganos del Estado) serán almacenados en la base de datos, de la página web.Ley N°19.628, Artículo 2. Para los efectos de esta ley se entenderá por: a)Almacenamiento de datos, la conservación o custodia de datos en un registro o banco de datos.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">5.&nbsp;</span>Los datos recabados por la página web, podrán ser transferidos a terceros, previo cumplimiento de los requisitos establecidos en la Ley N°19.628, la aceptación expresa por parte de los usuarios y en las referidas Recomendaciones.Ley N°19.628, <span style="color: rgb(0, 0, 0);">Título I, De la utilización de datos personales, Artículo </span><strong style="color: rgb(0, 0, 0);">4.</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">6.&nbsp;</span><strong style="color: rgb(31, 56, 100);"><em><u>PETCICLA.CL</u></em></strong>&nbsp;podrá comunicar a terceros, los datos estadísticos o datos económicos elaborados a partir de los datos personales de sus usuarios, con el consentimiento expreso del titular de los mismos, conforme a las disposiciones legales que regulen la materia.Ley N°19.628, <span style="color: rgb(0, 0, 0);">Título I, De la utilización de datos personales, Artículo 4.</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">7.&nbsp;</span><span style="color: rgb(0, 0, 0);">El usuario podrá en todo momento ejercer los derechos consagrados en la Ley Nº 19.628. (</span>Ley N°19.628, <span style="color: rgb(0, 0, 0);">Título&nbsp;&nbsp;II. De los derechos de los titulares de datos. Artículo 12.) En específico, podrá:</span></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(0, 0, 0);">&nbsp;</strong></p>
                                                                <p><span style="color: rgb(0, 32, 96);">·&nbsp;</span><strong style="color: rgb(34, 42, 53);">POLÍTICAS DE COOKIES DE LA PÁGINA WEB </strong><strong style="color: rgb(31, 56, 100);">PETCICLA.CL</strong></p>
                                                                <p><strong style="color: rgb(34, 42, 53);">&nbsp;</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">¿QUÉ SON LAS COOKIES?</strong><span style="color: rgb(34, 42, 53);">&nbsp;Es toda información contenida en un archivo o programa informático alojada en un sitio web y almacenado en el navegador del usuario. Para que su visita a nuestro sitio web sea atractiva y para permitir el uso de ciertas funciones, utilizamos las llamadas cookies, para salvaguardar nuestros intereses legítimos y también para optimizar nuestras presentaciones en la página web, en el contexto de un equilibrio de intereses.</span></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">&nbsp;</strong></p>
                                                                <p><strong style="color: rgb(34, 42, 53);">¿CUÁLES SON LAS FUNCIONES DE LAS COOKIES?:</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">1.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Recordar accesos</strong><strong>:</strong>&nbsp;conocer si se ha visitado la página para actuar en consecuencia, por ejemplo mostrando o no cierto contenido, recordar a un usuario, entre otros. Cuando un usuario introduce su nombre de usuario y contraseña, se almacena una&nbsp;cookie&nbsp;para que no tenga que estar introduciéndolas para cada página del servidor. Una cookie no identifica a una persona, sino a una combinación de computadora de la clase de computación-navegador-usuario.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">2.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Conocer información</strong><strong>:</strong>&nbsp;sobre los hábitos de navegación, de los usuarios, para brindarles una mejor experiencia de navegación en nuestro sitio web, adaptándonos a sus necesidades. </p>
                                                                <p class="ql-align-justify">&nbsp;</p>
                                                                <p><strong style="color: rgb(34, 42, 53);">¿QUÉ NO ES UNA COOKIE?</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 0, 0);">Las Cookies, no son un programa informático malicioso, estos archivos no constituyen; un virus, ni un troyano, ni un gusano, ni spam, ni spyware, ni abre ventanas pop-up.</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">&nbsp;</span></p>
                                                                <p><strong style="color: rgb(34, 42, 53);">¿QUÉ INFORMACIÓN ALMACENA UNA&nbsp;COOKIE?</strong></p>
                                                                <p class="ql-align-justify">Nuestras&nbsp;cookies&nbsp;no almacenan información sensible de los usuarios de esta página web, como los son; claves de tarjetas de crédito o débitos u otros datos bancarios, fotografías, documentos de identificación nacional, Pasaportes, credenciales, cédulas de identidad, DNI o algún tipo de información personal. </p>
                                                                <p class="ql-align-justify">Los datos que guardan en esta página web son de carácter técnico, preferencias personales, personalización de contenidos, entre otros. El servidor web no le asocia a usted como persona, solo asocia a su navegador web. </p>
                                                                <p class="ql-align-justify">&nbsp;</p>
                                                                <p><strong style="color: rgb(34, 42, 53);">TIPOS O CLASES DE&nbsp;COOKIES. </strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">1.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Cookies&nbsp;técnicas</strong><span style="color: rgb(34, 42, 53);">: Estas permiten saber cuándo está navegando un humano o una aplicación automatizada, cuándo navega un usuario anónimo y uno registrado, tareas básicas para el funcionamiento de cualquier web dinámica.</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">2.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Cookies&nbsp;de análisis:</strong><span style="color: rgb(34, 42, 53);">&nbsp;Recogen información sobre el tipo de navegación que está realizando, las secciones que más utiliza, productos consultados, franja horaria de uso, idioma, entre otros datos relacionados de este tipo.</span></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">3.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Cookies&nbsp;publicitarias:</strong><span style="color: rgb(34, 42, 53);">&nbsp;Muestran publicidad en función de su navegación, su país de procedencia, idioma, región, entre otros datos relacionados.</span></p>
                                                                <p><span style="color: rgb(34, 42, 53);">4.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Las&nbsp;cookies propias</strong><span style="color: rgb(34, 42, 53);">: Son las cookies generadas por la página que está visitando.</span></p>
                                                                <p><span style="color: rgb(34, 42, 53);">5.&nbsp;</span><strong style="color: rgb(34, 42, 53);">Las&nbsp;cookies de terceros</strong><span style="color: rgb(34, 42, 53);">: Son las cookies generadas por servicios o proveedores externos, (como por ejemplo; Google, entre otras páginas web) como también las redes sociales que usted haya visitado con anterioridad o tenga acceso desde esta página web por medio de algún enlace.</span></p>
                                                                <p>&nbsp;</p>
                                                                <p><strong style="color: rgb(34, 42, 53);">CONSECUENCIAS DE LA DESACTIVACIÓN DE LAS COOKIES.</strong></p>
                                                                <p class="ql-align-justify">Cuando usted como usuario de alguna plataforma web desactiva estos archivos de cookies, estará limitando o cercenando capacidades técnicas y herramientas propias de las cookies, lo cual limitaran realizar tareas como:&nbsp;</p>
                                                                <p><span style="color: rgb(0, 0, 0);">&nbsp;</span></p><p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">1.&nbsp;</span>Compartir contenidos en algunas de las redes sociales como por ejemplo; Facebook, Twitter.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">2.&nbsp;</span>Limitará la adaptación de los contenidos a sus preferencias personales, como suele ocurrir en las tiendas online.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">3.&nbsp;</span>No podrá acceder al área personal de esa web, como por ejemplo:&nbsp;(Mi cuenta, Mi perfil&nbsp;o&nbsp;Mis pedidos).</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">4.&nbsp;</span>Tiendas online: Le será imposible realizar compras online, tendrán que ser telefónicas o visitando la tienda física si es que dispone de ella.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">5.&nbsp;</span>No será posible personalizar sus preferencias geográficas como franja horaria, divisa o idioma.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">6.&nbsp;</span>El sitio web no podrá realizar analíticas web sobre visitantes y tráfico en la web, lo que dificultará que la web sea competitiva.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">7.&nbsp;</span>No podrá escribir en el blog, no podrá subir fotos, publicar comentarios, valorar o puntuar contenidos. </p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">8.&nbsp;</span>La web no podrá saber si usted es un humano o una aplicación automatizada que publica&nbsp;spam.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">9.&nbsp;</span>No se podrá mostrar publicidad sectorizada, lo que reducirá los ingresos publicitarios de la web.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">10.&nbsp;</span>Todas las redes sociales usan&nbsp;cookies, si las desactiva no podrá utilizar ninguna red social.</p>
                                                                <p><span style="color: rgb(0, 0, 0);">&nbsp;</span></p><p><strong style="color: rgb(34, 42, 53);">DESACTIVACIÓN O ELIMINACIÓN DE COOKIES</strong></p>
                                                                <p class="ql-align-justify">En cualquier momento los usuarios podrán ejercer su derecho de desactivación o eliminación de cookies de este sitio web. Además de eliminar las cookies, también pueden bloquear, de forma general o particular para un dominio específico. Estas acciones se realizan de forma diferente en función del navegador que esté usando.&nbsp;</p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(50, 62, 79);">¿Cómo puedo eliminar las cookies?</strong></p>
                                                                <p class="ql-align-justify">Para eliminar las&nbsp;cookies&nbsp;de este sitio web en particular, usted como usuario debe ir a la configuración de su navegador y allí podrá buscar las cookies asociadas al dominio en cuestión y proceder a su eliminación.</p>
                                                                <p class="ql-align-justify">&nbsp;</p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(50, 62, 79);">Configuración de las Cookies</strong><strong style="color: rgb(0, 32, 96);">. </strong>Los navegadores web&nbsp;son en esencia un&nbsp;software,&nbsp;aplicación&nbsp;o&nbsp;programa&nbsp;que permite el acceso a las páginas web, interpretando la información de distintos tipos de archivos y sitios web para que estos puedan ser visualizados, estos programas soportan las cookies, sin embargo, un usuario puede normalmente elegir si las cookies deberían ser utilizadas, bloqueadas, eliminadas o no.</p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(0, 32, 96);">&nbsp;</strong></p><p><strong style="color: rgb(34, 42, 53);">EXCLUSIÓN DE RESPONSABILIDADES EN CUANTO AL MANEJO DE LAS COOKIES.</strong></p>
                                                                <p class="ql-align-justify">Las cookies de terceros, no provienen de este sitio web que usted está visitando, sino de sitos web ajenos a nuestra responsabilidad, (otras páginas web o plataformas digitales que no son administradas por nosotros), Razón por la cual <span style="color: rgb(0, 0, 0);">este página web</span>, no es responsable de los datos e información que terceras personas (páginas web, aplicaciones móviles, plataformas digitales de cualquier tipo) puedan obtener de usted, dado que estas no están bajo nuestro control, manejo y responsabilidad.</p>
                                                                <p class="ql-align-justify">&nbsp;</p>
                                                                <p><strong style="color: rgb(34, 42, 53);">CONSENTIMIENTO SOBRE EL USO DE LAS COOKIES POR PARTE DE LOS USUARIOS </strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(31, 56, 100);"><em><u>PETCICLA.CL</u></em></strong>, informa a todos sus usuarios que este sitio web se utilizan las cookies para personalizar el contenido y los anuncios, además para ofrecer funciones de redes sociales y analizar el tráfico, utilizamos nuestras cookies con fines de marketing y publicidad, para ofrecerle al usuario la mejor disponibilidad de nuestro productos y servicios. Habiendo informado debida y adecuadamente en un lenguaje sencillo y claro, todas y cada una de nuestras políticas de cookies, tiene usted la responsabilidad de leerlas, por lo cual usted acepta nuestras políticas de cookies sin oposición a las mismas si continua utilizando nuestro sitio web.</p>
                                                                <p class="ql-align-justify"><span style="color: rgb(34, 42, 53);">&nbsp;</span></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(34, 42, 53);">MEDIOS CORPORATIVOS DE LA EMPRESA.</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 32, 96);">·&nbsp;</span><strong style="color: rgb(0, 32, 96);">Teléfono. +56 9 4027 1976</strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 32, 96);">·&nbsp;</span><strong style="color: rgb(0, 32, 96);">Página Web. https://www.<em><u>&nbsp;</u>petcicla.cl</em></strong></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 32, 96);">·&nbsp;</span><strong style="color: rgb(0, 32, 96);">Correo Electrónico. </strong><a href="mailto:contacto@petcicla.cl" target="_blank" style="color: rgb(0, 0, 255);"><strong><u>contacto@petcicla.cl</u></strong></a></p>
                                                                <p class="ql-align-justify"><span style="color: rgb(0, 32, 96);">·&nbsp;</span><a href="https://www.google.com/search?sa=X&amp;hl=es-419&amp;sxsrf=ALeKk01_zOSEWDmnZdIb5G9Ky4bpec1OuQ:1607620688646&amp;q=rm+investment+spa+antofagasta+direcci%C3%B3n&amp;stick=H4sIAAAAAAAAAOPgE-LVT9c3NMywTC-pSqsq15LNTrbSz8lPTizJzM-DM6wSU1KKUouLF7FqFOUqZOaVpRaX5KbmlSgUFyQqJOaV5KclpicWlyQqpGQWpSYnZx7enAcAcHtHHFsAAAA&amp;ludocid=4552578450107531456&amp;ved=2ahUKEwj649Hg9cPtAhUD1VkKHUBxAYAQ6BMwF3oECCQQAg" target="_blank" style="color: rgb(0, 32, 96);"><strong>Dirección</strong></a><strong style="color: rgb(0, 32, 96);">:&nbsp;República de Chile</strong></p>
                                                                <p><strong style="color: rgb(34, 42, 53);">&nbsp;</strong></p>
                                                                <p class="ql-align-justify"><strong style="color: rgb(0, 32, 96);">Al momento de registrarse en algunos de nuestros servicios dentro de la página web, usted de forma tácita e irrevocable, acepta todas las normas del Contrato de Plataforma Digital, de </strong><strong style="color: rgb(59, 56, 56);"><em><u>PETCICLA.CL</u></em></strong><strong style="color: rgb(0, 32, 96);">, asume sus Derechos y Responsabilidades contractuales y jurídicas, siempre contando en todo momento con su consentimiento en pleno ejercicio de sus facultades como persona.</strong></p>
                                                                <p><br></p>                                                                                                                                            
                                                                <p></p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </section>
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
            </main>
        </div>
    </div>
@endsection
@section('js')
<script>
</script>
@endsection
